# cloudbuild.yaml

steps:
# 1. Pull the latest image to use as a cache.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/secret-alerts-system:latest || exit 0']

# 2. Build the container image, tagging it with both the commit SHA and 'latest'.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from'
    - 'gcr.io/$PROJECT_ID/secret-alerts-system:latest'
    - '-t'
    - 'gcr.io/$PROJECT_ID/secret-alerts-system:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/secret-alerts-system:latest'
    - '.'

# 3. Deploy to Cloud Run, now with the memory setting included.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'secret-alerts-system'
    - '--image=gcr.io/$PROJECT_ID/secret-alerts-system:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=1Gi'  # Recommended: Set the memory for the service.

# This tells Cloud Build to automatically push the built images.
images:
- 'gcr.io/$PROJECT_ID/secret-alerts-system:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/secret-alerts-system:latest'

options:
  logging: CLOUD_LOGGING_ONLY