# cloudbuild.yaml
steps:
# 1. Pull the latest image to use as a cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/secret-alerts-system:latest || exit 0']

# 2. Build the container image, tagging it with BOTH the commit SHA and 'latest'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from'
    - 'gcr.io/$PROJECT_ID/secret-alerts-system:latest'
    - '-t'
    - 'gcr.io/$PROJECT_ID/secret-alerts-system:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/secret-alerts-system:latest'
    - '.'

# 3. Push the images BEFORE deploying
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/secret-alerts-system:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/secret-alerts-system:latest']

# 4. Deploy to Cloud Run (now the image exists in the registry)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'secret-alerts-system'
    - '--image=gcr.io/$PROJECT_ID/secret-alerts-system:$COMMIT_SHA'  # Your original syntax was correct
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=1Gi'

options:
  logging: CLOUD_LOGGING_ONLY